# Generated by Django 6.0 on 2026-03-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
