# Generated by Django 6.0 on 2026-03-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('not-started', 'Not Started'), ('in-progress', 'In Progress'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not-started', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('admin_feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('project_id', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('assigned_to', models.CharField(max_length=50)),
                ('status', models.CharField(default='todo', max_length=50)),
                ('accepted', models.BooleanField(default=False)),
                ('priority', models.CharField(default='medium', max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('comments', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
