# Generated by Django 6.0 on 2026-04-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='start_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_to_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
