# Generated by Django 6.0 on 2026-04-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_milestone_delivery_date_milestone_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
