# Generated by Django 6.0 on 2026-04-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
