# Generated by Django 6.0 on 2026-03-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('contact', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('client_name', models.CharField(max_length=200)),
                ('project_details', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
            ],
        ),
    ]
